### PR TITLE
Remove stray `.d.ts` file

### PR DESCRIPTION
**Pull request by mrm007**
It was missed in #1197

### CODE REVIEW

**Review by askoufis — APPROVED** [review]
That change was also never released. IMO it should've been, but 🤷.

**Comment by mrm007** [comment]
@askoufis now we have a changeset

**Review by mattcompiles — APPROVED** [review]
Thanks @mrm007! 🍻 
I actually added it but it got forced pushed over and I didn't realise 🤷

**Comment by brandonpittman** [comment]
https://github.com/vanilla-extract-css/vanilla-extract/pull/1197

I swore I did this…

**Comment by askoufis** [comment]
> #1197
> 
> Did my PR not get included with in the release?

Your changes have been released. [The release](https://github.com/vanilla-extract-css/vanilla-extract/releases/tag/%40vanilla-extract%2Fcss%401.14.0) is pointing to the PR that added the changeset.

**Comment by brandonpittman** [comment]
> > #1197
> > Did my PR not get included with in the release?
> 
> Your changes have been released. [The release](https://github.com/vanilla-extract-css/vanilla-extract/releases/tag/%40vanilla-extract%2Fcss%401.14.0) is pointing to the PR that added the changeset.

Thanks. The notes mentioned someone else as fixing it and I wondered if my PR disappeared into the ether. 😊

**Pull request merged**
