### PR TITLE
export types needed for typescript inference with esm

### PR DESCRIPTION
**Pull request by pkieltyka**
additional fixes for https://github.com/vanilla-extract-css/vanilla-extract/issues/739 similar to https://github.com/vanilla-extract-css/vanilla-extract/pull/890 which was missing a few types necessary for export

### CODE REVIEW

**Comment by johndarmstrong** [comment]
bump - could someone take a look at exporting these additional types? This is currently a blocker from using our component library in modern tooling, without having to patch vanilla extract in our build pipeline.

**Comment by pkieltyka** [comment]
Strange a trivial fix like this takes so much time to review / merge. Where the maintainers at?

**Comment by awhiteside1** [comment]
Just ran into this issue as well - I think I was able to workaround it by basically isolating the theme contract  and disabling emitting declarations for that package, but definitely not ideal for something  fairly trivial to handle properly.

**Review by awhiteside1 — APPROVED** [review]

**Comment by awhiteside1** [comment]
Might have been a lack of changeset, added here: https://github.com/pkieltyka/vanilla-extract/pull/1

**Comment by michaeltaranto** [comment]
Hey, we were discussing this one today and want to understand the use case a bit more clearly before we take on the increase to the public API footprint.

Can you provide a simple reproduction example demoing the use case?

**Comment by jungpaeng** [comment]
@michaeltaranto Hi, I'm using Node16 moduleResolution.

Here's the problem I'm currently having, I'll write it briefly to clarify the error.

  ```ts
// Button.css.ts
import { recipe, RecipeVariants } from '@vanilla-extract/recipes';

export type ButtonContainerVariants = RecipeVariants<typeof buttonContainer>;

export const buttonContainer = recipe({
  variants: {
    test: {
      test1: {
        display: 'flex',
      },
    },
  },
});
```

```tsx
// Button.tsx
import React from 'react';

import { ButtonContainerVariants } from './Button.css.js';

type Props = ButtonContainerVariants & {
  test?: 'test1';
  children?: React.ReactNode;
};
```

```tsx
export function Button({ ...props }: Props) {
  return <button {...props} />;
}

// Boo.tsx
function Boo() {
  return <Button />;
}
```

There's an issue with the test's type inference on the Button inside the Boo component. Here's a picture of it
image

The reason for this issue is as follows.

Node16 moduleResolution and above can only read exported types, so the `VariantGroups` I return as a result of `RecipeVariants` are not exported, causing this issue.

This is causing me a lot of inconvenience. Is there something wrong with my explanation?

**Comment by mrm007** [comment]
Hi @jungpaeng & @pkieltyka ,

I was not able to reproduce the issue. I used the code from this comment https://github.com/vanilla-extract-css/vanilla-extract/pull/907#issuecomment-1474265207 and type inference on the `Button` inside the `Boo` component worked as expected:

image

In my attempt to reproduce the issue, I have tested with:

- `pnpm@7.30.0` with default config
- `typescript@5.0.4` or `typescript@4.9.5` installed
- `"type": "module"` in `package.json`
- `"module": "ESNext"` (or `NodeNext`) and `"moduleResolution": "node16"` (or `nodenext`) in `tsconfig.json`

Let me know if I missed something. A repo with more specific code and steps to reproduce would be helpful. We'll close the issue for now, but if you can provide more details, we'll be happy to reopen it.

**Pull request closed without merging**
