### PR TITLE
vite: Create compiler during `buildStart` instead of `configResolved`

### PR DESCRIPTION
**Pull request by himself65**
Related: https://github.com/dai-shi/waku/pull/559

### CODE REVIEW

**Comment by askoufis** [comment]
@himself65 Thanks for the PR. Could you provide some more context on what the issue is and how this change fixes it?

I can sort of see how `createCompiler` is better placed in the `buildStart()` hook, but I don't think the `!compiler` check is achieving anything here. Were you observing the `compiler` being recreated, leading to a bug?

**Comment by himself65** [comment]
> @himself65 Thanks for the PR. Could you provide some more context on what the issue is and how this change fixes it?
> 
> I can sort of see how `createCompiler` is better placed in the `buildStart()` hook, but I don't think the `!compiler` check is achieving anything here. Were you observing the `compiler` being recreated, leading to a bug?

Yeah, the issue is when we call `resolveConfig` in node.js, `buildEnd` won't be called in this case, so that the node.js process cannot exit successfully

**Comment by himself65** [comment]
> `!compiler` check

Oh, that is my mistake

**Comment by askoufis** [comment]
> > @himself65 Thanks for the PR. Could you provide some more context on what the issue is and how this change fixes it?
> > I can sort of see how `createCompiler` is better placed in the `buildStart()` hook, but I don't think the `!compiler` check is achieving anything here. Were you observing the `compiler` being recreated, leading to a bug?
> 
> Yeah, the issue is when we call [`resolveConfig`](https://github.com/dai-shi/waku/blob/2852bd169991f95b468101177efc651136a65f87/packages/waku/src/lib/builder/build.ts#L600-L602) in node.js, `buildEnd` won't be called in this case, so that the node.js process cannot exit successfully

Oh I understand now. So `resolveConfig` calls the `configResolved` hooks of plugins, so a compiler is created but never destroyed. Makes sense to me. I'll add a changeset.

**Review by askoufis — APPROVED** [review]

**Comment by askoufis** [comment]
@himself65 This has been released https://github.com/vanilla-extract-css/vanilla-extract/releases/tag/%40vanilla-extract/vite-plugin%404.0.5

**Pull request merged**
