### PR TITLE
Add `globalImport`

### PR DESCRIPTION
**Pull request by graup**
Based on the discussion at https://github.com/seek-oss/vanilla-extract/discussions/600

The rule format mirrors the CSS spec: https://developer.mozilla.org/en-US/docs/Web/CSS/@import

### CODE REVIEW

**Comment by mattcompiles** [comment]
Couple of concerns with adding an `@import` API: 

- You can use it to import other local CSS files which most bundlers will try to interpret. This leads to scenarios that will break as relative imports will not work currently. If we merge #647 this scenario may be able to be improved but not sure it'd ever be a good idea anyway. 
- In what scenario is using CSS import an ideal solution? As mentioned in the [linked discussion](https://github.com/seek-oss/vanilla-extract/discussions/600#discussioncomment-2227318), using CSS import leads to request waterfalls. Why wouldn't I just add the assets directly to the HTML?

**Comment by graup** [comment]
* Yeah I'm also a bit concerned about local imports. That's a can of worms we likely don't want to open.
* If you link to the `woff2` files directly, I believe that has a couple disadvantages: I suspect Google is doing some magic to only deliver the file types needed for the user's browser. Also if they ever update the rules, you'll miss out on that.

The better workaround is importing the CSS using a `<link>` tag. That is fine, we just have to tell our consumers do that.

So yeah, this is not a must-have feature.

**Comment by graup** [comment]
Since there hasn't been additional interest in this feature, I'm gonna close my PR!

**Comment by SalahAdDin** [comment]
It would be a great feature man @graup !

**Pull request closed without merging**
