### PR TITLE
Update addFileScope to handle commonjs source files

### PR DESCRIPTION
**Pull request by roginfarrer**
I think this should address the issues noted in #940 and #850 and #963

In my case, I had `.css.js` files in `node_modules` that looked something like this:

```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

const _css = require('@vanilla-extract/css');

var myStyle = _css.style({});

exports.myStyle = myStyle;
```

When run through `addFileScope`, this would prepend an ESM style import to a CJS file, and would cause errors like those noted in the issues above.

I'm not 100% sure this is the fix for all scenarios (I think there may be more cases across the VE codebase where this may happen), but I wanted to push this up for discussion. It's not the most elegant way to ascertain whether a file is ESM or CJS, but it worked in my brief testing.

### CODE REVIEW

**Comment by mihkeleidast** [comment]
I can confirm that this resolves my issues similar to #940 and #963, though I still get `NonErrorEmittedError` sometimes (for that the workaround in #679 works at the moment).

**Comment by mihkeleidast** [comment]
@roginfarrer perhaps you can add a changeset as well, then there shouldn't be any more things blocking this...

**Review by mattcompiles — COMMENTED** [review]
Thanks for the PR. @roginfarrer 

I'm ok with this change but feel a little uncomfortable owning the detection of whether a file is ESM or CJS. Could we instead use a tested library to handle this? I'd suggest `hasESMSyntax` from [mlly](https://www.npmjs.com/package/mlly?activeTab=readme).

**Comment by roginfarrer** [comment]
@mattcompiles Good call with using a library 👍🏻. Updated!

**Review by mattcompiles — APPROVED** [review]
Thanks for the PR mate 🍻

**Pull request merged**
